name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, dependency-upgrades ]

env:
  GO_VERSION: "1.19.10"
  PLUGIN_GO_VERSION: "1.19.10" # should match Kubo i guess
  KUBO_VERSION: "v0.21.0-rc1"

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
        path: nopfs

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Tests
      working-directory: nopfs
      run: go test -v -timeout 15m -coverprofile=coverage.txt -covermode=atomic .

    - name: Coverage
      uses: codecov/codecov-action@v3
      with:
        directory: nopfs

  check:
    name: "Static, syntax and spelling checks"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: ipfs/kubo
        fetch-depth: 2
        ref: ${{ env.KUBO_VERSION }}
        path: kubo

    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
        path: nopfs

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Install misspell
      run: go install github.com/client9/misspell/cmd/misspell@latest

    - name: Check
      working-directory: nopfs
      run: make check

  plugin:
    name: "Plugin"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: ipfs/kubo
        fetch-depth: 2
        ref: ${{ env.KUBO_VERSION }}
        path: kubo

    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
        path: nopfs

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.PLUGIN_GO_VERSION }}

    - name: Plugin
      working-directory: nopfs
      run: make plugin
